version: "3.9"
services:
  frontend:
    image: realsahilthakur/frontend-app:latest
    ports:
      - "8080:80"
    networks:
      - app-net

  backend:
    image: realsahilthakur/backend-app:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=pass
    ports:
      - "5000:5000"
    networks:
      - app-net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:

volumes:
  dbdata:
