version: "3.9"
services:
  # Simple nginx with static files
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - app-net
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - source: frontend_html
        target: /usr/share/nginx/html/index.html
      - source: frontend_css
        target: /usr/share/nginx/html/main.css
      - source: frontend_time_js
        target: /usr/share/nginx/html/time.js

  backend:
    image: realsahilthakur/backend-app:v2.0
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=pass
    ports:
      - "5000:5000"
    networks:
      - app-net
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-net:
    driver: overlay

volumes:
  dbdata:

configs:
  frontend_html:
    file: ./src/FRONTEND/swarm-index.html
  frontend_css:
    file: ./src/FRONTEND/main.css
  frontend_time_js:
    file: ./src/FRONTEND/time.js
