services:
  frontend:
    build: ./src/FRONTEND
    ports:
      - "8081:80"

  backend:
    build: ./src/BACKEND
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
