apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-microservices-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/realsahilthakur/dockerized-microservices-app.git
    targetRevision: master
    path: helm-chart  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
