apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.port }}
      # nodePort: 30080


# 3 namespaces
