FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY main.css /usr/share/nginx/html/main.css
COPY main.js /usr/share/nginx/html/main.js
COPY time.js /usr/share/nginx/html/time.js
COPY default.conf /etc/nginx/conf.d/default.conf