apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/realsahilthakur/micro-service-application.git
    targetRevision: HEAD
    path: helm-charts/database-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3